name: build

on:
  push:
  pull_request:
  schedule:
    - cron: '10 3 * * *'

jobs:
  build:
    if: ${{ startsWith(github.repository, 'ruby/') || github.event_name != 'schedule' }}
    name: build (${{ matrix.ruby }} / ${{ matrix.os }})
    strategy:
      matrix:
        ruby: [ '3.3' ]
        os: [ windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # 'bundle install' and cache
    - run: choco install gperf
      if: ${{ matrix.ruby == 'mswin' }}
    - name: Run compile
      run: bundle exec rake compile
    - run: |
        set `ruby -rdate -e 'puts $".grep(/date_core\.so/)'` `find -name date_core.so`
        ls -l "$@"
        nm "$@"
      shell: bash
    - name: Run test
      run: bundle exec rake test
