name: build

on:
  push:
  pull_request:
  schedule:
    - cron: '10 3 * * *'

jobs:
  ruby-versions:
    uses: ruby/actions/.github/workflows/ruby_versions.yml@master
    with:
      engine: cruby-truffleruby
      min_version: 2.6

  build:
    if: ${{ startsWith(github.repository, 'ruby/') || github.event_name != 'schedule' }}
    name: build (${{ matrix.ruby }} / ${{ matrix.os }})
    needs: ruby-versions
    strategy:
      matrix:
        ruby: ${{ fromJson(needs.ruby-versions.outputs.versions) }}
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        exclude:
          - ruby: head
            os: windows-latest
          - ruby: truffleruby # need truffleruby 24.2+
            os: ubuntu-latest
          - ruby: truffleruby # need truffleruby 24.2+
            os: macos-latest
          - ruby: truffleruby
            os: windows-latest
          - ruby: truffleruby-head
            os: windows-latest
        include:
          - ruby: mingw
            os: windows-latest
          - ruby: mswin
            os: windows-2022
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5
    - name: Set up Ruby
      uses: ruby/setup-ruby-pkgs@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # 'bundle install' and cache
        msys2: gperf
        choco: gperf
    - name: Run test
      run: bundle exec rake compile test
